language: node_js
node_js:
  - "8"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
branches:
  only:
  - master

stages:
  - install
  - build
  - deploy

jobs:
  include:
    - stage: install
      script: cd website/ && yarn

    - stage: build
      script: cd website/ && yarn build

    - stage: deploy
      script: cd website/ && yarn deploy  
