language: node_js
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
branches:
  only:
  - master

jobs:
  include:
    - stage: install
      script: cd website/ && yarn

    - stage: build
      script: cd website/ && yarn build

    - stage: deploy
      script: cd website/ && yarn deploy  
